package:
  name: "coreutils"
  version: "9.8"
  type: "binary"
  architecture: "x86_64"
  description: "GNU core utilities - basic file, shell and text manipulation utilities"
  maintainer: "APGer <anmitali198@gmail.com>"
  license: "GPL-3.0"
  homepage: "https://www.gnu.org/software/coreutils/"
  tags: ["gnu", "utilities", "core", "shell", "posix"]
  dependencies: 
    - "libc6"
    - "libacl1"
    - "libattr1"
    - "libgmp10"
    - "libselinux1"
    - "libcap2"
  conflicts: 
    - "uutils-coreutils"
    - "uutils"
    - "busybox"
    - "toybox"
    - "sbase"
    - "9base"
  provides: ["coreutils"]
  replaces: 
  conf: []

source:
  url: "https://ftp.gnu.org/gnu/coreutils/coreutils-{{VERSION}}.tar.xz"

build:
  dependencies: 
    - "build-essential"
    - "libgmp-dev"
    - "libattr1-dev"
    - "libacl1-dev"
    - "libselinux1-dev"
    - "libcap-dev"
    - "gettext"
    - "texinfo"
  script: |
    ./configure \
      --prefix=/usr \
      --enable-install-program=arch,hostname \
      --enable-no-install-program=kill,uptime
    make -j$(nproc)

install:
  script: "make DESTDIR=\"$DESTDIR\" install"
